---
title: "ADS_Assignment"
author: "Kaixin Yu"
student ID: 1118795
output:
  html_document: default
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("corrplot")
library('plot.matrix')
library(corrplot)
library(reshape2)
library(ggplot2)
```

 
Question 1
Q1.1
```{r}
# create TC sources
TC_par<- par(mfrow=c(2,3))
TC_1<- c(rep(rep(c(1,0), each =15), 8))
TC_2<- c(rep(0,20), rep(rep(c(1,0),c(20,25)), length.out=220))
TC_3 <- c(rep(rep(c(1,0), c(25, 60-25)), length.out=240))
TC_4 <- c(rep(rep(c(1,0), c(15, 40-15)), length.out=240))
TC_5 <- c(rep(rep(c(1,0), c(20, 40-20)), length.out=240))
TC_6 <- c(rep(rep(c(1,0), c(25, 40-25)), length.out=240))
TC <- matrix(c(TC_1, TC_2, TC_3, TC_4, TC_5, TC_6), 240,6)
TC <- scale(TC)

# plot TC sources
for (i in (1:6)){
  plot(TC[,i], type='l')
}

par(TC_par)
```

Q 1.2
```{r}
# plot correaltion matrix of TC 
par(mfrow = c(1,1))
par(mar=c(5.1, 4.1, 4.1, 4.1))
plot(cor(TC), main="Correlation of time sources")
```

Q 1.3
```{r}
# create 6 SMs and plot them out
par(mfrow=c(2,3))
SM_1<- matrix(rep(0, 441), 21,21)
SM_1[c(2:6), c(2:6)] <- 1
plot(SM_1, border=NA)

SM_2<- matrix(rep(0, 441), 21,21)
SM_2[c(2:6), c(15:19)] <- 1
plot(SM_2, border=NA)

SM_3<- matrix(rep(0, 441), 21,21)
SM_3[c(8:13), c(2:6)] <- 1
plot(SM_3, border=NA)

SM_4<- matrix(rep(0, 441), 21,21)
SM_4[c(8:13), c(15:19)] <- 1
plot(SM_4, border=NA)

SM_5<- matrix(rep(0, 441), 21,21)
SM_5[c(15:19), c(2:6)] <- 1
plot(SM_5, border=NA)

SM_6<- matrix(rep(0, 441), 21,21)
SM_6[c(15:19), c(15:19)] <- 1
plot(SM_6, border=NA)
```

```{r}
# plot the correlation matrix of SM
par(mfrow = c(1,1))
par(mar=c(3.1, 4.1, 4.1, 4.1))

SM <- matrix(c(as.vector(SM_1), as.vector(SM_2), as.vector(SM_3), as.vector(SM_4), as.vector(SM_5), as.vector(SM_6)), 6, 441)

corrplot(cor(t(SM)),title = "Correlation Matrix of tmpSM", addCoef.col="black", method="color")
```

Q 1.4
```{r}
# create noise and plot correlation matrix for TC 
set.seed(123)
par(mfrow=c(1,2))
TC_noise <- matrix(rnorm(240*6, mean=0, sd=sqrt(0.25)), 240,6)
TC_noise_cor <- cor(TC_noise)
corrplot(TC_noise_cor, method='color', addCoef.col="black", title="CM for TC noise", mar=c(0,0,1,0))

# create noise and plot correlation matrix for SM
SM_noise <- matrix(rnorm(6*441, mean=0, sd=sqrt(0.015)), 6, 441)
SM_noise_cor <- cor(t(SM_noise))
corrplot(SM_noise_cor, method='color', addCoef.col="black", title="CM for SM noise",mar=c(0,0,1,0))
```

as the plots shown, the noise of both two sources are independent.

```{r}
# plot the histogram for both noise source and add distribution curve
hist(as.vector(TC_noise), prob=TRUE)
curve(dnorm(x, mean=0, sd = sqrt(1.96*0.25)), col="red", lwd=2, add=TRUE)

hist(as.vector(t(SM_noise)), prob=TRUE)
curve(dnorm(x, mean=0, sd = sqrt(1.96*0.015)), col="red", lwd=2, add=TRUE)
```

Both TC and SM noise look have a normal distributuion, and satisfied the 1.96$\sigma$.

```{r}
# visualize the correlation between the noise product and observed variables
par(mfrow = c(1,1))
par(mar=c(5.1, 4.1, 4.1, 4.1))
noise_product <- TC_noise%*%SM_noise
corrplot(cor(noise_product), method="color")
```
The correlation heap map show non correlation

Q1.5
```{r}
X <- (TC+TC_noise)%*%(SM+SM_noise)

# check the cross product
(dim(TC))
(dim(SM_noise))
(dim(TC_noise))
(dim(SM))
```

The products exists.

```{r}
# get sample
set.seed(123)
par(mfrow = c(1,1))
par(mar=c(5.1, 4.1, 4.1, 4.1))
sample<-data.frame(n=1:240, X[, sample(ncol(X), size=100)])

# plot the sample
sample_gg <- melt(sample, id.vars="n")
ggplot(sample_gg, aes(x=n, y=value, col=variable))+ geom_line()
```

```{r}
# calculate variance of all variables
X_var<- var(X)[1,]
plot(X_var)
X<- scale(X)
```

Q2

Q2.1
```{r}
D <- TC
# retrieve A by LSR
A_lsr <- solve(t(D)%*%D)%*%t(D)%*%X
# retrieve D by LSR
D_lsr <- X%*%t(A_lsr)
```

```{r}
# plot retrieval sources
par(mfrow=c(1,2))
plot(matrix(abs(A_lsr[1,]), 21,21),border=NA)
ts.plot(D_lsr[,1])

plot(matrix(abs(A_lsr[2,]), 21,21), border=NA)
ts.plot(D_lsr[,2])

plot(matrix(abs(A_lsr[3,]), 21,21), border=NA)
ts.plot(D_lsr[,3])

plot(matrix(abs(A_lsr[4,]), 21,21), border=NA)
ts.plot(D_lsr[,4])

plot(matrix(abs(A_lsr[5,]), 21,21), border=NA)
ts.plot(D_lsr[,5])

plot(matrix(abs(A_lsr[6,]), 21,21), border=NA)
ts.plot(D_lsr[,6])

# scatter plot
par(mfrow = c(1,1))
par(mar=c(5.1, 4.1, 4.1, 4.1))
plot(D_lsr[,3], X[,30])
```